# Generated by Django 4.2.7 on 2024-01-06 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='title',
            field=models.CharField(help_text='Название ссылки для индентификации', max_length=100, null=True, validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
