# Generated by Django 4.2.7 on 2024-01-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_url_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='company',
            field=models.CharField(help_text='Компания', max_length=50, null=True),
        ),
    ]
